name: Fetch RSS Feeds

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 */2 * * *' # Runs every 2 hours

jobs:
  fetch-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Medium RSS Feed
        run: |
          curl -L -o _data/medium_feed.xml "https://medium.com/@narasimhakarthik/feed" || echo "Failed to fetch Medium feed"

      - name: Fetch Substack RSS Feed
        run: |
          curl -L -o _data/substack_feed.xml "https://neuraforge.substack.com/feed" || echo "Failed to fetch Substack feed"

      - name: Check for changes and commit
        run: |
          git config --global user.name 'RSS Feed Bot'
          git config --global user.email 'actions@github.com'
          
          # Add any new or changed feed files
          git add _data/*_feed.xml
          
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to RSS feeds."
          else
            git commit -m "Update RSS feeds $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi